
# vim: set foldmarker={{,}} foldlevel=0 foldmethod=marker:
#
# NOTE:
#   查看折叠内容的方法:
#      za: normal 模式下按 za, 表示当光标在关闭折叠上时打开之, 在打开折叠上时关闭之;
#          在打开的折叠内部任意处按 za, 也会关闭折叠.
#      zA: 是 za 的递归操作, 是针对嵌套折叠的场景.


# --- 主题配置 {{

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# 除了这里默认配置的 powerlevel10k 主题, 还可以使用一些简洁的主题,
# 比如: ys, robbyrussell, amuse, agnoster, random
# doc: https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# }}

# --- 基础配置 {{

# 解决 source ~/.zshrc 和 ~/.tmux.conf 中 set-environment -g PATH 导致的 PATH 变量值重复的问题.
# $PATH 值的来源:
#   1) /etc/paths
#   2) /etc/paths.d/*
#   3) ~/.zshrc
#   4) ~/.zshenv
#   5) ~/.tmux.conf 中的 set-environment -g PATH ""
typeset -U PATH

# oh-my-zsh 安装路径.
# NOTE:
#   $ZSH/cache/completions 路径默认在 $FPATH 中, 以后有新命令的补全文件可以放在此路径下, 比如:
#     gopass completion zsh > $ZSH/cache/completions/_gopass
#     exec zsh 或 omz reload
export ZSH="$HOME/.oh-my-zsh"

# 为 zsh 定制的内容的放置目录.
export ZSH_CUSTOM="$ZSH/custom"

# 标准插件存放在: $ZSH/plugins/
# 定制插件存放在: $ZSH_CUSTOM/plugins/
# NOTE:
# 1) 光标移到下面的 README.md 文件, 按 gf 可以打开帮助文件, 按 ctrl o 返回到当前文件.
#   vi-mode:  ~/.oh-my-zsh/plugins/vi-mode/README.md
#   tmux:  ~/.oh-my-zsh/plugins/tmux/README.md
#   git:  ~/.oh-my-zsh/plugins/git/README.md
#   gitignore: ~/.oh-my-zsh/plugins/gitignore/README.md
#   history: ~/.oh-my-zsh/plugins/history/README.md
#   brew:  ~/.oh-my-zsh/plugins/brew/README.md
#   extract:  ~/.oh-my-zsh/plugins/extract/README.md
#   web-search: ~/.oh-my-zsh/plugins/web-search/README.md
#   emoji: ~/.oh-my-zsh/plugins/emoji/README.md
#   colorize: ~/.oh-my-zsh/plugins/colorize/README.md
#   colored-man-pages: ~/.oh-my-zsh/plugins/colored-man-pages/README.md
#   zsh_reload: ~/.oh-my-zsh/plugins/zsh_reload/README.md
#   sudo: ~/.oh-my-zsh/plugins/sudo/README.md
#   timer: ~/.oh-my-zsh/plugins/timer/README.md
#   themes: ~/.oh-my-zsh/plugins/themes/README.md
#   urltools: ~/.oh-my-zsh/plugins/urltools/README.md
#   copyfile: ~/.oh-my-zsh/plugins/copyfile/README.md
#   copypath: ~/.oh-my-zsh/plugins/copypath/README.md
#   aliases: ~/.oh-my-zsh/plugins/aliases/README.md
# 2) 启用的插件, 会将插件目录加入到环境变量 $FPATH 中.
plugins=(
    vi-mode
    # tmux
    git
    gitignore
    z
    history
    brew
    extract
    web-search
    emoji
    zsh-autosuggestions
    zsh-syntax-highlighting
    colorize
    colored-man-pages
    sudo
    themes
    urltools
    copyfile
    copypath
    aliases
)


# 解决粘贴较长的内容到终端命令行时速度太慢的问题.
# NOTE:
#   1) 此配置必须放到 source $ZSH/oh-my-zsh.sh 之前.
#   2) 第一次配置之后, 如果想使当前 shell 立即生效, 可执行: exec zsh
DISABLE_MAGIC_FUNCTIONS=true

source $ZSH/oh-my-zsh.sh

# 设置系统默认语言, 避免终端出现中文乱码.
export LANG=en_US.UTF-8

# 专门用来解决 ranger.vim 乱码的问题.
export LC_ALL=en_US.UTF-8

# 默认的编辑器, git、crontab 等会默认使用.
export EDITOR=nvim

# 私有配置单独存放的文件.
source $HOME/.zshrc.private

# }}


# --- alias 配置 {{

alias vi="nvim"
alias cp='cp -i'
alias mv='mv -i'

alias ll="eza -l -g --icons --git"

# *** dotfiles 项目可执行文件

# 将 bin 目录加入到 PATH.
export PATH="$HOME/.dotfiles/bin:$PATH"

# Vim/Neovim & Alacritty 主题相关命令
alias o=opacity
alias cs=colorscheme
alias fs=font-size
alias c=colors-print
alias hex=print-256-hex-colors
alias icons=print-icons

# 调节系统音量
alias vol=audio-volume

# 便捷批量 ssh 连接或恢复连接远程服务器
alias s=ssh-sessions

# *** 快速打开 dotfiles 的几种主要配置文件

alias zrc='nvim ~/.dotfiles/zsh/zshrc'
# alias vrc='nvim ~/.dotfiles/vim/vimrc'
# alias tconf='nvim ~/.dotfiles/tmux/tmux.conf'
alias atoml='nvim ~/.dotfiles/alacritty/alacritty.toml'

# *** 快速切换到常用的目录

alias d="cd ~/Documents"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"

# *** 其他

# 列出正在监听的tcp连接.
alias lsof_tcp="lsof -aP -i TCP -s TCP:LISTEN"

# brew install jesseduffield/lazygit/lazygit
# doc: https://github.com/jesseduffield/lazygit
alias lg=lazygit

# 用来统计某个用户提交的代码行数信息. i.e. $ gs someusername
alias gs="git log --numstat --author"
# }}


# --- 其他配置 {{

# 用于 git commit 的签名.
export GPG_TTY=$(tty)

# *** fzf (https://github.com/junegunn/fzf)
# brew install fzf
# $(brew --prefix)/opt/fzf/install
export FZF_DEFAULT_OPTS='--height 60% --layout=reverse --border'
alias ff="vim \$(fzf)"
# Useful key bindings and fuzzy completion.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Enable shell completion.
autoload -U compinit; compinit

# 当在命令行中输入无法匹配的文件名时，shell 不会生成任何错误消息，而只是将该字符串作为参数传递给命令.
setopt no_nomatch

# }}